language: elixir
otp_release:
- 17.4
addons:
  postgresql: '9.3'
before_script:
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.create --no-start, ecto.migrate --no-start
deploy:
  provider: heroku
  app: obesebird-api
  buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
  strategy: git-ssh
  api_key:
    secure: htTNRv28Z7ZvwylG3EKdkHwx2irQn7vitdqs9MgIKsmONlwwJajMO8Oa7PTPyIRGVKSEwP6YDGtYQDQgR8M8xeTNwD+HC4gWMex6jURa54r+l6tLOCEcj5+q3WC5HRsEw8wMI7Qug8ymig0v2WjGLfWa0Uc7IH0LwuG7bLLv+3Qcyzw6zVCo5hAKL1oXyMVzaOZWPuS9AcVRFL0VQo8XKcon0H0qEBYvqns1y8FlEkUue7xVuhMqIy3haYwZnk/SxktNrtVurOYSuRrcTyEgE4acE7HxELiiCy6B7NaEclUL2DsgX85PiCd1o2uufAddJDi4ZHafS2ExxaNgjYFEr0Lz0CjWvN0cK/2snzNv1AWx25vU1vYeXbvWR55yMrekk97TlVwqqpegS2Jqd5Cecla1BS9ykAUqo69nLAoM7w7PYJmNFcfCnTIQ0R3uhLeexESDcF3+qYb8jfLPOhGe628CLYXlyduZioWpaOm48nkCr5rSK8PJa61DDZhQVTV6J1bRg87gbAMzMgWtE1/jpKQFKFSvCC/MXwkyyLW92xJhUiEINioi8r+z0jDbQFdmT4ueKUVxLIoY8D9lCaAzwhytp+0MViyqi+wVloyItHZy9piwHD9gfgIKNLg54xP0txz++3SCj8VQBQaq8bK94r7vwzsRk0l/QdcQ5CIVMX4=
after_deploy:
  - heroku run "mix ecto.migrate" -a obesebird_api
